# Generated by Django 4.1.7 on 2023-05-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almosthumanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=500)),
                ('subscription_id', models.CharField(default='', max_length=500)),
                ('payment_id', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
