# Generated by Django 4.1.7 on 2023-05-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almosthumanapp', '0002_stripe_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe_subscription',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
