# Generated by Django 4.1.7 on 2023-05-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almosthumanapp', '0003_stripe_subscription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripe_subscription',
            old_name='payment_id',
            new_name='price_id',
        ),
    ]
