# Generated by Django 4.1.7 on 2023-05-09 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almosthumanapp', '0005_alter_stripe_subscription_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe_subscription',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
