# Generated by Django 4.1.7 on 2023-05-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almosthumanapp', '0006_alter_stripe_subscription_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripe_subscription',
            name='status',
        ),
    ]
